# Generated by Django 5.1.1 on 2024-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sativa', '0003_alter_booking_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=1, upload_to='restaurant/menu/'),
            preserve_default=False,
        ),
    ]
