# Generated by Django 5.1.1 on 2024-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sativa', '0004_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spapricing',
            name='image',
            field=models.ImageField(default=1, upload_to='spa/pricing/'),
            preserve_default=False,
        ),
    ]
