# Generated by Django 5.1.1 on 2024-10-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sativa', '0008_remove_blog_image_alter_blogcomment_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
